version: "3.2"
services:
  mysql:
    restart: always
    container_name : mysql-docker
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: shalini123
       MYSQL_DATABASE : institution
    ports:
      - "6033:3306"
    volumes:
     - ./mysql-data:/var/lib/mysql
  studentapplication:
    container_name : studentapplication
    restart: always
    image: studentcallapp
    ports:
      - "8081:8081"
    depends_on:
      - mysql
  rest-call-to-student-application:
    container_name : restcalltostudentapplication 
    image: restcallapp 
    ports:
      - "8082:8082"
    depends_on:
      - studentapplication
  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "2c32b11e5217febbd8386c61520684b8b653NRAL"
    restart: unless-stopped
